### ISSUE TITLE
Release Dataset

### ISSUE THREAD

**Issue by luomancs** [MhmdSaiid/RuleBert#1]
Hi there, 

When will you release the dataset used in the paper? 

Thanks

**Comment by mojsaeed** [comment]
Hello @luomancs,
Excuse me for the late reply as I am on vacation. The dataset and code will be released next week. I will ping you once uploaded.

**Comment by mojsaeed** [comment]
Hello @luomancs 
Sorry for the late response.
The datasets, models, and code are up.
